### ISSUE TITLE
Suggestion: add an example or a few screenshots

### ISSUE THREAD

**Issue by Naereen** [alex-ball/tikzgamemap#1]
Hi,
This project sounds very exciting, but it would definitely help if you could add an example (of a PDF produced by these scripts?) or a few screenshots!
(see for instance, https://github.com/Naereen/LaTeX-article-with-Pokemon-numbering#demo)
Good luck!

**Comment by alex-ball** [comment]
I am gratified for your immediate interest in this package. It is something I have been experimenting with on and off for many years, but in the past few days I decided it was good enough to work up into a proper package, thus converted it to DTX, put it under version control and started this repo.

This package is still quite far from the point of release. If you could check back when I have tagged a release, I will be glad to accept feedback.

**Comment by Naereen** [comment]
Sure!
